### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by maverick74** [syranez/tab-reload-on-select#2]
I have another suggestion (since using it i've encountered this problem):

There are a few pages i would like to open exceptions to. Pages like Gmail, WebSkype, radio pages, other pages with private SaaS systems, etc. I have them "Pinned" and they have their own systems that keep them updated. Updating them is, actually, not a good idea...

**Comment by syranez** [comment]
Yeah, an exception list would be great.

My first tought is an exception list with url entrys. Thus I can filter specific urls or an whole domain, e. g:

<pre>
Exception list:
* https://github.com/syranez/tab-reload-on-select/issues/2 (no reload on this page ever)
* https://github.com/ (no reload on any github.com-Page ever)
</pre>

Protocols must always match except http/https.

But maybe I will limit this on domains first.

And then a "Disable reload on this domain"-Button would be nice :D

**Comment by maverick74** [comment]
@syranez  History Zebra ( https://github.com/kafene/history-zebra ) may serve as inspiration ;)

**Comment by syranez** [comment]
@maverick74 Thank you very much for your patience and input.

I've just released version 1.3.0

Major feature: Tab reload on selects now has an icon! ;)

Another major feature is "exclude host". I did not implent a list but a button. From the readme:

> The add-on adds a button to the browser's toolbar. The button activates and deactivates tab reload on the domain of the URL.
> 
>The button has a colorized hourglass if tab reload is active on the domain. Otherwise the icon is a grey x.

I hope you like it!

**Comment by maverick74** [comment]
@syranez Hi!!! Thank you!!! It works great!!!

The button is very intuitive!!! :)
Another option i've been thinking about would be to put the option when right-clicking a tab but that, while still near the mouse pointer, would not give it as much visibility as the button does!

**Comment by syranez** [comment]
Great!

I've put your idea on https://github.com/syranez/tab-reload-on-select/wiki and close the issue now. I will not implement the list feature in the near future.
