### ISSUE TITLE
Feature request: Reload unloaded tab only

### ISSUE THREAD

**Issue by nfp0** [syranez/tab-reload-on-select#4]
The default behavior when Firefox restores a session is to only load tabs when you click on them. And even so, it only loads a cached version of the tab.
When I reopen my browser and Firefox loads a tab, I expect it to have fresh content from the server, and not the stale content from days ago.

This feature would make it so an inactive tab would be reloaded with fresh content from the server when it is first loaded by clicking on it after a session restore.

**Comment by syranez** [comment]
That would indeed be a good feature.

I will look into it.

**Comment by syranez** [comment]
Fixed with commit 8eefe82ed9186f7991dbc45c2c9db09d9e1e0525
Release 1.4.0 will be coming soon.
