### ISSUE TITLE
Does not work with Waterfox classic 2019.12

### ISSUE THREAD

**Issue by BobHD** [syranez/tab-reload-on-select#5]
The latest version does not work with Waterfox classic 2019.12, and the previous ones although flagged as working do not load.
Thanks for looking int it.

**Comment by BobHD** [comment]
Installing it on 2019.10 and then upgrading Waterfox works.

**Comment by BobHD** [comment]
Modifying the json file to support 56 as minimum version works also.

**Comment by syranez** [comment]
Thank you. I've set the strict minimum version back to 56 and released version 1.4.2.

**Comment by BobHD** [comment]
On 1/3/2020 12:12, Michael Nowack wrote:
> Thank you. I've set the strict minimum version back to 56 and released 
> version 1.4.2.

Thanks, that was fast.

I find that 1.4.2 has a default compared to 1.3.1.1: it does not keep 
the scroll position.

With 1.3.1.1, the tab reloads and I don't have to scroll if was not on 
top, while with 1.4.2 it goes on top, and I almost hace to scroll to the 
position I was.

I use it mainly on a site that looks like:

where I am scrolled down.

With the new version, it goes on top:



and I have to scroll to see the useful content.

Not a big deal, but having to do it every time gets old rapidly.

At the moment, I put back m modified 1.3.1.1 and disabled the updates.

Best Regards,


-- 
Robert Benaroya
Avenue des Chasseurs 49
1410 Waterloo
Belgique
Portable +32 (0)468 53 59 00
Fixe +32 (0)2 851 3881

**Comment by syranez** [comment]
I did not notice this behaviour yet. I'll look into it in #6.

Thank you
